name: Deployer

on: 
  pull_request:
    branches: 
      - main

jobs:
  check-shell:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: luizm/action-sh-checker@v0.1.10
        with:
          sh_checker_comment: false
          sh_checker_exclude: "src mvnw mvnw.cmd gradlew"

  build_and_pytest:
    runs-on: ubuntu-latest
    name: Setup Environment
    env:
      REGISTRY: docker.io
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup QEMU (Cross-Arch Integ.)
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & PyTest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false

